[general]
email = "salaho.khadir@gmail.com"

[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#3182ce"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a202c"
textColor = "#ffffff"
